version: "3.8"

services:
  frontend:
    build:
      context: ./DockerComposeFrontend
      dockerfile: ./Dockerfile.fe
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.be
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
