FROM node:18-alpine

# Set the working directory to /app (or any directory you want in the container)
WORKDIR /app

# Copy the package.json file first to take advantage of Docker cache
COPY ./package.json ./

# Install the dependencies
RUN npm install

# Expose the port (check if 5432 is the right port for your frontend app)
EXPOSE 3000

# Copy the rest of the application code
COPY . .

# Run the app
CMD ["npm", "run", "dev"]